### PR TITLE
Genx mod

### PR DESCRIPTION
**Pull request by aneeshamanocha**
I have made changes for columns for network.csv, generators_data.csv, generators_variability.csv, and load_data.csv. I haven't made any changes to the fuels_data.csv dataframe yet.

### CODE REVIEW

**Comment by gschivley** [comment]
@aneeshamanocha have you committed changes and pushed them to fork @sambuddhac made? The only changed file in this PR is `environment.yml` and it looks like the changes are from one of my commits.

**Comment by aneeshamanocha** [comment]
Hey @gschivley,  I retried committing changes (now with changes to fuels_data.csv and time_series_mapping.csv). Are the new changes I've made visible now?

**Comment by gschivley** [comment]
@aneeshamanocha Yes, I see the commits now. Is this an ASAP review type of thing? I'm also looking at #115 and doing some other work for the group.

**Comment by aneeshamanocha** [comment]
No, not urgent at all. Just wanted to let you know that the updates for
genX modular are ready to go and the PR should be ready.

**Comment by gschivley** [comment]
@aneeshamanocha what is the purpose of `post_processing.py`? Is it supposed to be a script that is used to format inputs for the open-source GenX? All of the other changes seem pretty minor and should be easy to review.

**Comment by aneeshamanocha** [comment]
Apologies, that script is for myself and my WECC study. Please feel free to
ignore that, it wasn't supposed to be pushed.

**Pull request merged**
