### PR TITLE
Add float format = "%g" to several csv output functions

### PR DESCRIPTION
**Pull request by cfe316**
I don't know how powergenome works and so someone should really check
this. I didn't add float_format to places where it already existed.
I also didn't add it to the pudl extraction since that seemed to be an
intermediate operation.

### CODE REVIEW

**Comment by gschivley** [comment]
Thanks @cfe316. There are two places where files are written to CSV:
1. Storing downloaded data so it doesn't need to be fetched again (EIA's open data and BLS consumer price index).
2. Writing input files for GenX

I think downloaded data should be saved as-is. GenX input files should be saved with reduced sig figs. This method might be best for files where formatting is consistent across columns. Generators_data.csv is much more varied, and it might be better to use the built-in `GenX.round_col_values()` function with [this dictionary](https://github.com/PowerGenome/PowerGenome/blob/045205af87bb9329a2a51bd6e612b61f45e1f65c/powergenome/GenX.py#L31-L43) of column:sig fig inputs.

**Comment by gschivley** [comment]
I'm not sure if this is needed anymore. In commit 0ddb5cd6584c2485bd30015568077c3aab3581dc I added column-specific formatting for the generators data file and a general output formatting for writing results to file. Is there anything else you think I missed?

**Comment by cfe316** [comment]
I'll take your word for it! I'm actually not (yet) a primary user of PowerGenome, so I haven't tried it out.

**Comment by gschivley** [comment]
Ok. I'll close this for now but we can revisit if necessary.

**Pull request closed without merging**
